#pragma once

// Vial
#define VIAL_KEYBOARD_UID {0xD3, 0x75, 0x68, 0xFA, 0x98, 0x48, 0x07, 0x01}
#define VIAL_UNLOCK_COMBO_ROWS { 0,0 }
#define VIAL_UNLOCK_COMBO_COLS { 0,1 }

// Define options
#define DYNAMIC_KEYMAP_LAYER_COUNT 7
#define TAPPING_TERM 230
#define PERMISSIVE_HOLD

// RGB options
#define RGBLIGHT_SLEEP
#define RGBLIGHT_LIMIT_VAL 50
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYERS_RETAIN_VAL
